### ISSUE TITLE
Ollamac should open to a New Chat automatically

### ISSUE THREAD

**Issue by epheterson** [kevinhermawan/Ollamac#103]
When launching Ollamac the UI is not immediately usable, you first have to click an existing chat or start a new one.

It'd be great if the UI always opened with a new chat waiting, similar to how most Chatbot sites initially load.

If the user selects an existing chat on open, we should not preserve this automatically-created new chat, that should disappear from the list (or never be added to the list until that chat is used).

**Comment by kevinhermawan** [comment]
Great suggestion! Thanks

**Comment by tobiasfabian** [comment]
+1  
The focus should be on the prompt input field, to be able to write right away.
