### ISSUE TITLE
Ollamac crashing on startup

### ISSUE THREAD

**Issue by VilterPD** [kevinhermawan/Ollamac#108]
Strangely recently, ollamac seems to be crashing on startup. I tried uninstalling and reinstalling via brew, but it still persists:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Ollamac [2161]
Path:                  /Applications/Ollamac.app/Contents/MacOS/Ollamac
Identifier:            com.kevinhermawan.Ollamac
Version:               3.0.0 (12)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-09-20 14:30:53.5389 +0200
OS Version:            macOS 14.6.1 (23G93)
Report Version:        12
Anonymous UUID:        F691E297-9FE6-D221-B31D-4546EAC8318B

Time Awake Since Boot: 200 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000019322cf28

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [2161]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	       0x19322cf28 _assertionFailure(_:_:file:line:flags:) + 268
1   Ollamac                       	       0x102d01740 0x102cd0000 + 202560
2   Ollamac                       	       0x102d02c08 0x102cd0000 + 207880
3   Ollamac                       	       0x102d02790 0x102cd0000 + 206736
4   SwiftUI                       	       0x1afb5bdfc 0x1aeeed000 + 13037052
5   Ollamac                       	       0x102d027d4 0x102cd0000 + 206804
6   dyld                          	       0x183197154 start + 2476

Thread 1:
0   libsystem_pthread.dylib       	       0x18351cd20 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x18351cd20 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x18351cd20 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x00006000001e9008   x1: 0x0000000200000003   x2: 0x0000000000000000   x3: 0x00006000013fc4c0
    x4: 0x00006000013fc500   x5: 0x0000000000000013   x6: 0x0000000000000020   x7: 0x0000000000000000
    x8: 0xfffffffe00000000   x9: 0x0000000200000003  x10: 0x0000000000000003  x11: 0x00000000a2003813
   x12: 0x00000000000007fb  x13: 0x00000000000007fd  x14: 0x00000000a220400a  x15: 0x000000000000000a
   x16: 0x00000000a2003813  x17: 0x0000000000004000  x18: 0x0000000000000000  x19: 0x0000000102e3f6c0
   x20: 0x00006000001e9000  x21: 0x0000000000000000  x22: 0x000000000000000b  x23: 0x0000000000000018
   x24: 0x000000000000001c  x25: 0x0000000102e3f170  x26: 0xf000000000000070  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016d12f600   lr: 0x000000019322cf28
    sp: 0x000000016d12f530   pc: 0x000000019322cf28 cpsr: 0x60001000
   far: 0x0000000000000000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x102fd0000 -        0x102fdbfff libobjc-trampolines.dylib (*) <7d6ca1cb-c5e6-38b6-9618-2c580486fc6b> /usr/lib/libobjc-trampolines.dylib
       0x103414000 -        0x103457fff org.sparkle-project.Sparkle (2.6.4) <0e273e3e-459c-3fa6-9a86-4754c5cc30ff> /Applications/Ollamac.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle
       0x102cd0000 -        0x102e53fff com.kevinhermawan.Ollamac (3.0.0) <76a9d5f4-085f-3e07-8c6a-854c781260e8> /Applications/Ollamac.app/Contents/MacOS/Ollamac
       0x1931f3000 -        0x193750fff libswiftCore.dylib (*) <7db1818b-1d9a-328e-821b-21a33442746a> /usr/lib/swift/libswiftCore.dylib
       0x1aeeed000 -        0x1b0bd0fff com.apple.SwiftUI (5.6.2) <0ccf2597-869c-37ef-aded-ce62f6ac3c77> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
       0x183191000 -        0x18321a507 dyld (*) <f635824e-318b-3f0c-842c-c369737f2b68> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x18351b000 -        0x183527fff libsystem_pthread.dylib (*) <e03e8478-6f5c-3d21-a79a-58408f514000> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=828.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=828.3M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
CoreData Object IDs               4112K        2 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           814.2M       22 
MALLOC guard page                   96K        6 
STACK GUARD                       56.1M        4 
Stack                             9808K        4 
VM_ALLOCATE                         16K        1 
__AUTH                            1706K      314 
__AUTH_CONST                      27.7M      512 
__CTF                               824        1 
__DATA                            12.8M      498 
__DATA_CONST                      27.3M      519 
__DATA_DIRTY                      2128K      188 
__FONT_DATA                          4K        1 
__LINKEDIT                       525.7M        4 
__OBJC_RO                         71.9M        1 
__OBJC_RW                         2200K        1 
__TEXT                           622.7M      536 
dyld private memory                272K        2 
mapped file                       31.3M        4 
shared memory                      624K        7 
===========                     =======  ======= 
TOTAL                              2.2G     2630 

-----------
Full Report
-----------

{"app_name":"Ollamac","timestamp":"2024-09-20 14:30:53.00 +0200","app_version":"3.0.0","slice_uuid":"76a9d5f4-085f-3e07-8c6a-854c781260e8","build_version":"12","platform":1,"bundleID":"com.kevinhermawan.Ollamac","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.6.1 (23G93)","roots_installed":0,"name":"Ollamac","incident_id":"BA2822FA-46B4-4EEF-8081-B15A86DBFD3D"}
{
  "uptime" : 200,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,9",
  "coalitionID" : 1060,
  "osVersion" : {
    "train" : "macOS 14.6.1",
    "build" : "23G93",
    "releaseType" : "User"
  },
  "captureTime" : "2024-09-20 14:30:53.5389 +0200",
  "codeSigningMonitor" : 1,
  "incident" : "BA2822FA-46B4-4EEF-8081-B15A86DBFD3D",
  "pid" : 2161,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-09-20 14:30:48.1633 +0200",
  "procStartAbsTime" : 4751290052,
  "procExitAbsTime" : 4880292292,
  "procName" : "Ollamac",
  "procPath" : "\/Applications\/Ollamac.app\/Contents\/MacOS\/Ollamac",
  "bundleInfo" : {"CFBundleShortVersionString":"3.0.0","CFBundleVersion":"12","CFBundleIdentifier":"com.kevinhermawan.Ollamac"},
  "storeInfo" : {"deviceIdentifierForVendor":"D5102388-7C5A-50AD-B086-79ECFB280906","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.kevinhermawan.Ollamac",
  "crashReporterKey" : "F691E297-9FE6-D221-B31D-4546EAC8318B",
  "lowPowerMode" : 1,
  "codeSigningID" : "com.kevinhermawan.Ollamac",
  "codeSigningTeamID" : "84ZM7K56B5",
  "codeSigningFlags" : 570503953,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"4gMZquMDF6rkAxWq5QMTquYDFqrnAxiqFQCA0pYDAJTgAxSqWTQPlA==","atPC":"IAAg1CgAgFKJEoBS6BMAuekHAPlIAIBS6AMAOSAnALAA0CeRIycAsA=="},
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000001, 0x000000019322cf28","rawCodes":[1,6763499304],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":2161},
  "os_fault" : {"process":"Ollamac"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":14192,"threadState":{"x":[{"value":105553118269448},{"value":8589934595},{"value":0},{"value":105553137222848},{"value":105553137222912},{"value":19},{"value":32},{"value":0},{"value":18446744065119617024},{"value":8589934595},{"value":3},{"value":2717923347},{"value":2043},{"value":2045},{"value":2720022538},{"value":10},{"value":2717923347},{"value":16384},{"value":0},{"value":4343461568},{"value":105553118269440},{"value":0},{"value":11},{"value":24},{"value":28},{"value":4343460208},{"value":17293822569102704752},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6763499304},"cpsr":{"value":1610616832},"fp":{"value":6124926464},"sp":{"value":6124926256},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":6763499304,"matchesCrashFrame":1},"far":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":237352,"symbol":"_assertionFailure(_:_:file:line:flags:)","symbolLocation":268,"imageIndex":3},{"imageOffset":202560,"imageIndex":2},{"imageOffset":207880,"imageIndex":2},{"imageOffset":206736,"imageIndex":2},{"imageOffset":13037052,"imageIndex":4},{"imageOffset":206804,"imageIndex":2},{"imageOffset":24916,"symbol":"start","symbolLocation":2476,"imageIndex":5}]},{"id":14356,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"x":[{"value":6125481984},{"value":4103},{"value":6124945408},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6125481984},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6498143520},"far":{"value":0}}},{"id":14357,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"x":[{"value":6126055424},{"value":8963},{"value":6125518848},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6126055424},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6498143520},"far":{"value":0}}},{"id":14358,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"x":[{"value":6126628864},{"value":9475},{"value":6126092288},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6126628864},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6498143520},"far":{"value":0}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4345102336,
    "size" : 49152,
    "uuid" : "7d6ca1cb-c5e6-38b6-9618-2c580486fc6b",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4349575168,
    "CFBundleShortVersionString" : "2.6.4",
    "CFBundleIdentifier" : "org.sparkle-project.Sparkle",
    "size" : 278528,
    "uuid" : "0e273e3e-459c-3fa6-9a86-4754c5cc30ff",
    "path" : "\/Applications\/Ollamac.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle",
    "name" : "Sparkle",
    "CFBundleVersion" : "2039.1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4341956608,
    "CFBundleShortVersionString" : "3.0.0",
    "CFBundleIdentifier" : "com.kevinhermawan.Ollamac",
    "size" : 1589248,
    "uuid" : "76a9d5f4-085f-3e07-8c6a-854c781260e8",
    "path" : "\/Applications\/Ollamac.app\/Contents\/MacOS\/Ollamac",
    "name" : "Ollamac",
    "CFBundleVersion" : "12"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6763261952,
    "size" : 5627904,
    "uuid" : "7db1818b-1d9a-328e-821b-21a33442746a",
    "path" : "\/usr\/lib\/swift\/libswiftCore.dylib",
    "name" : "libswiftCore.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7229853696,
    "CFBundleShortVersionString" : "5.6.2",
    "CFBundleIdentifier" : "com.apple.SwiftUI",
    "size" : 30294016,
    "uuid" : "0ccf2597-869c-37ef-aded-ce62f6ac3c77",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/Versions\/A\/SwiftUI",
    "name" : "SwiftUI",
    "CFBundleVersion" : "5.6.2"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6494425088,
    "size" : 562440,
    "uuid" : "f635824e-318b-3f0c-842c-c369737f2b68",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6498136064,
    "size" : 53248,
    "uuid" : "e03e8478-6f5c-3d21-a79a-58408f514000",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 6493667328,
  "size" : 4214358016,
  "uuid" : "bb3df3d3-38bd-304c-9233-e43de95f1903"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=828.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=828.3M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nCoreData Object IDs               4112K        2 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           814.2M       22 \nMALLOC guard page                   96K        6 \nSTACK GUARD                       56.1M        4 \nStack                             9808K        4 \nVM_ALLOCATE                         16K        1 \n__AUTH                            1706K      314 \n__AUTH_CONST                      27.7M      512 \n__CTF                               824        1 \n__DATA                            12.8M      498 \n__DATA_CONST                      27.3M      519 \n__DATA_DIRTY                      2128K      188 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       525.7M        4 \n__OBJC_RO                         71.9M        1 \n__OBJC_RW                         2200K        1 \n__TEXT                           622.7M      536 \ndyld private memory                272K        2 \nmapped file                       31.3M        4 \nshared memory                      624K        7 \n===========                     =======  ======= \nTOTAL                              2.2G     2630 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "92c3d03d96810ccaeb0005191424361f74bf20d7",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "63f9578e238e7b23a1f3030a",
      "factorPackIds" : {

      },
      "deploymentId" : 240000005
    },
    {
      "rolloutId" : "6410af69ed1e1e7ab93ed169",
      "factorPackIds" : {

      },
      "deploymentId" : 240000011
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c47ab4cc-c9c3-4b5d-a87c-e2433ce02597",
      "experimentId" : "6639bc6ba73d460582162323",
      "deploymentId" : 400000006
    },
    {
      "treatmentId" : "45f4e2a5-551b-4bc2-a2dc-19c244dda8f8",
      "experimentId" : "6643969b3099cf28e049862f",
      "deploymentId" : 400000007
    }
  ]
}
}

Model: Mac14,9, BootROM 10151.140.19, proc 10:6:4 processors, 16 GB, SMC 
Graphics: Apple M2 Pro, Apple M2 Pro, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4388), wl0: Apr  4 2024 20:57:11 version 23.30.58.0.41.51.138 FWID 01-baea9d27
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Network Service: Tailscale, VPN (io.tailscale.ipn.macos), utun4
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by Filmdoneright** [comment]
Same for me

**Comment by kevinhermawan** [comment]
Have you tried installing manually without Homebrew?

**Comment by Filmdoneright** [comment]
> Have you tried installing manually without Homebrew?

Thanks for the quick reply:-D

I tried installing every version now, and the only version that doesn't crash is everything before version 2.0. I'm not using Homebrew.

**Comment by kevinhermawan** [comment]
Have you tried the solutions from these closed issues?

https://github.com/kevinhermawan/Ollamac/issues/64 & https://github.com/kevinhermawan/Ollamac/issues/65

**Comment by kevinhermawan** [comment]
You're welcome 😃

**Comment by VilterPD** [comment]
Yes, running `rm -rf ~/Library/Containers/com.kevinhermawan.Ollamac/Data/Library/Application\ Support/`

in terminal seems to resolve the Issue, thank you
