### ISSUE TITLE
Can't send messages

### ISSUE THREAD

**Issue by jamesofficer** [kevinhermawan/Ollamac#109]
Hey everyone,

Interested in trying out Ollamac, however I am unable to send any messages? It looks like the send button is disabled but it's hard to tell. No hotkeys work to send the message. I can create new chats and interact with the UI just fine, I just can't send any messages.

I checked the default localhost address (http://localhost:11434) and see "Ollama is running" when I view that address, so it seems to be connected. I can interact with Ollama via my CLI fine.

Ollamac 3.0.0
macOS Sonoma 14.5

Appreciate any help!

**Comment by kevinhermawan** [comment]
Hi @jamesofficer, are you sure you’ve selected the model? You can verify this in the right sidebar.

![CleanShot 2024-09-30 at 19 57 57@2x](https://github.com/user-attachments/assets/0be108f9-6ad2-46e0-8355-a7983b6a7adb)

**Comment by jamesofficer** [comment]
Oh yup, that was it. Looked like it was selected as the text was there but it wasn't 🤦 .

Appreciate the quick response!
