### ISSUE TITLE
Older history gone

### ISSUE THREAD

**Issue by lead0r** [kevinhermawan/Ollamac#110]
I'm not sure if this is an ollamac or ollama issue or maybe just a setting thing, but I didn't know where else to ask. I'm on macOS Sequoia 15.0.1.

After a few reboots where everything worked fine, today I suddenly had only yesterday's chat history (i.e., the three chats I used yesterday), but not the one's from before. I would like to keep my chats permanently. Is that possible?

I'm not sure if this is related to this, but I have my models on an external drive and have to set the folder using "launchctl setenv OLLAMA_MODELS". After a reboot I always have to do this, so when opening ollamac before that, the App obviously cannot find any models. Not sure if this might have caused loss of chat history?
I just created an environment.plist with the above command and hopefully I won't have to set the model folder in the future again

**Comment by kevinhermawan** [comment]
Hi @lead0r, first I want to clarify that the chat history is not belonging to Ollama, it's all in the Ollamac side and it will be there unless you manually remove the chat from the sidebar or you accidentally clean up the Ollamac storage (there is also a probable removed by cleaner app). In that case, has this always happened with the scenario you mentioned? Or has it only happened once?

**Comment by lead0r** [comment]
I'm sorry, I might have not looked right. I think everything I haven't manually deleted is still there

**Comment by johnalanwoods** [comment]
@kevinhermawan - fantastic app! - sorry to necro this thread - where is chat history stored?
