### ISSUE TITLE
Why background and the code font are both black? 

### ISSUE THREAD

**Issue by xuanhua** [kevinhermawan/Ollamac#111]
![image](https://github.com/user-attachments/assets/c4589d32-d265-4917-a735-4966244d7fec)

Hi,  Ollamac is great, but why it displayed bash code and the ground both in black ?  Or there is some settings I should change ?  Any help is appreciated.

**Comment by kevinhermawan** [comment]
Hi @xuanhua, it works well in my side (I’m using Llama 3.2 as shown in the screenshot below). Could you please restart the app and open it again? Also, which model do you use? I believe some models produce unstable code blocks.

![CleanShot 2024-10-18 at 05 59 41](https://github.com/user-attachments/assets/b4dd9be6-d464-4ee5-a816-68a31ed51f56)

**Comment by kevinhermawan** [comment]
Hmm, this is strange. Is it always this way when you create a new chat? I’ve tested it with the `deepseek` model, and it works without any issues.

![Ollamac 2024-10-18 19 32 18](https://github.com/user-attachments/assets/124e24f0-e86d-4e8f-a173-5844dad63e3d)

**Comment by xuanhua** [comment]
@kevinhermawan  yes,  for every code block, no matter what language it is in it. It always displayed with very dark background. Currently I'm using Version 3.0.0 (12)

**Comment by kevinhermawan** [comment]
Wait, have you enabled experimental code highlighting in the settings?

![CleanShot 2024-10-23 at 02 13 46](https://github.com/user-attachments/assets/a32fc7da-d1f7-4f93-922b-46cf36f431bf)

**Comment by xuanhua** [comment]
@kevinhermawan yes, by default  code highlighting is disabled.  I think you should enable it by default.

**Comment by xuanhua** [comment]
@kevinhermawan enabling code highlighting resloved my issue, thanks anyway.

**Comment by kevinhermawan** [comment]
For now, it’s marked as an experimental feature, so you’ll need to manually enable it. Thanks for confirming, I’ll close this issue.
