### ISSUE TITLE
Cancel generation

### ISSUE THREAD

**Issue by ThimbleThings** [kevinhermawan/Ollamac#13]
I think it would be very useful to be able to stop the model from generating output using a button in the chat interface.
Currently I have to wait until the model is done with generating output, even when I already know the generated output is not of interest to me, costing valuable compute time.

**Comment by kevinhermawan** [comment]
Hi @ThimbleThings, thank you for bringing up this interesting feature request. I will certainly explore the feasibility of this feature and look into ways it could be integrated.

**Comment by kevinhermawan** [comment]
Implemented in [version v1.1.0](https://github.com/kevinhermawan/Ollamac/releases/tag/v1.1.0)
