### ISSUE TITLE
Regeneration seems to use incorrect context

### ISSUE THREAD

**Issue by MaxKlyukin** [kevinhermawan/Ollamac#15]
Love the feature, but stumbled upon strange behavior, regenerates response seemed to be a bit out of the chat's context.
 At first I thought it looses context completely, but after a bit of experimentation I thing it might be using previous generations of the response.

**Comment by kevinhermawan** [comment]
I've noticed that quirky behavior too. Funny thing, it seems like it's been addressed in another PR. This fix should be part of the next release.

**Comment by kevinhermawan** [comment]
Implemented in [version v1.1.0](https://github.com/kevinhermawan/Ollamac/releases/tag/v1.1.0)
