### ISSUE TITLE
[Bug] Switching chats during generation

### ISSUE THREAD

**Issue by mattbisme** [kevinhermawan/Ollamac#17]
While messing around with the app I noticed that I could switch between chats while it was generating. However, upon switching chats, the generation continued in the active chat. It just combines the generated text with the last response.

Let me know if any clarity is needed about this.

**Comment by kevinhermawan** [comment]
Oh, good catch! I totally missed that behavior with switching chats during generation. I'll dive into this and see what's going on. Thanks for flagging it!
