### ISSUE TITLE
User configurable baseURL

### ISSUE THREAD

**Issue by tphakala** [kevinhermawan/Ollamac#2]
I need to connect to Ollamac API running on remote server, it seems that baseURL is hard coded in current version

    var baseURL: URL {
        URL(string: "http://localhost:11434")!
    }

Would it be possible to make this user configurable?
HTTPS (TLS) should also be supported for remote API.

**Comment by kevinhermawan** [comment]
Yes, I'm working on this!

**Comment by jensenpat** [comment]
Any updates on this? Would be great for a Preferences dialog.

**Comment by luboszima** [comment]
+1

**Comment by kevinhermawan** [comment]
Hey everyone, thanks for being patient. This is the most requested feature in Ollamac, and if I have the time, I'll work on it this weekend. Hopefully, we can release this feature and code highlighting (#72) in the next update. 😁

**Comment by kevinhermawan** [comment]
Hey everyone! Finally, we can close this issue now. Check out the features in the [new update](https://github.com/kevinhermawan/Ollamac/releases/tag/v2.1.0)! 😉
