### ISSUE TITLE
First message fails when starting new chat

### ISSUE THREAD

**Issue by johnnyclem** [kevinhermawan/Ollamac#28]
when you start a new chat (with any model), the first response will come back as either \n or the first token in the reponse, then if you re-prompt the response comes back correctly.
<img width="1512" alt="Screenshot 2023-12-09 at 11 54 04 AM" src="https://github.com/kevinhermawan/Ollamac/assets/477808/7c9bbce3-02b2-49be-8c84-fea3c6c50c31">

**Comment by kevinhermawan** [comment]
Fixed in [version v1.1.1](https://github.com/kevinhermawan/Ollamac/releases/tag/v1.1.1)
