### ISSUE TITLE
"Send" button keyboard shortcut

### ISSUE THREAD

**Issue by felixkreuk** [kevinhermawan/Ollamac#3]
Hi, thanks for the nifty mac app! 
Is there a keyboard shortcut for the send button? 
If not then maybe cmd+enter is a good candidate :) 

Thanks in advance for considering this!

**Comment by kevinhermawan** [comment]
Hi @felixkreuk, thanks for your suggestion. I'm currently exploring the idea of streamlining the message sending process. The plan is to make the `Enter` key for sending messages and `Shift+Enter` for new lines, in line with the standard practices of other chat apps. 😄

**Comment by felixkreuk** [comment]
Sgtm!Thanks,FelixOn 10 Nov 2023, at 21:52, Kevin Hermawan ***@***.***> wrote:﻿
Hi @felixkreuk, thanks for your suggestion. I'm currently exploring the idea of streamlining the message sending process. The plan is to make the Enter key for sending messages and Shift+Enter for new lines, in line with the standard practices of other chat apps. 😄

**Comment by kevinhermawan** [comment]
I've successfully implemented a shortcut for the send button by pressing `Enter` (#4). However, tracking the `Shift` key hold has been challenging. I believe I've found an effective solution: adding an 'expand' button for users who prefer editing in a larger text editor. This addition will also simplify the process of inserting new lines.

**Comment by kevinhermawan** [comment]
Hi folks! Implemented in [version 1.0.1](https://github.com/kevinhermawan/Ollamac/releases/tag/v1.0.1) 😃

**Comment by felixkreuk** [comment]
Thanks a lot Kevin, works great!
