### ISSUE TITLE
[Bug] If you delete models from ollama, the ui does not update its list

### ISSUE THREAD

**Issue by ageorgios** [kevinhermawan/Ollamac#32]
If you delete models from ollama, the ui does not update its list

It would be better if the list of models was created on start of the application or even every time the settings appear.

**Comment by mattbisme** [comment]
I've noticed this as well. Seems like it's Ollamac that's "remembering" and nothing to do with the Ollama server itself?

**Comment by kevinhermawan** [comment]
Hi folks, the current flow keeps the model existing to avoid losing the chat that uses that model. But I have a plan to improve the flow in Ollamac v2 😃

**Comment by mattbisme** [comment]
> I have a plan to improve the flow in Ollamac v2 😃

I'm very happy to hear this. In the meantime, what `plist` do I have to delete to reset the list? My menu is getting a bit out of hand from just experimenting with, and then deleting, various models. 😅

**Comment by kevinhermawan** [comment]
> Do I have to delete to reset the list?

Unfortunately, uninstalling the app is currently the only solution. 😄 My apologies for this oversight. Let's fix this in v2!

**Comment by owenzhao** [comment]
At least add a (legacy) so we can easily choose when create a new conversation.

**Comment by kevinhermawan** [comment]
Just released [v2.0.0](https://github.com/kevinhermawan/Ollamac/releases/tag/v2.0.0). And this case will not happen again in the next version. Thank you!
