### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by antonengelhardt** [kevinhermawan/Ollamac#36]
It would be useful, if this application could be downloaded and updated via [Homebrew](https://brew.sh) for Mac.

**Comment by kevinhermawan** [comment]
Hmm, I think we don't need a Homebrew. It's straightforward to install Ollamac. All you need to do is download it from GitHub and install it once. To check for updates, simply go to the Ollamac menu and click on the `Check for Update...` option. If there is an update available, a popup will automatically appear. See the image below:

![Check for Update...](https://github.com/kevinhermawan/Ollamac/assets/84965338/2247cc57-66f6-4c04-898b-2e63fa1f6258)

**Comment by antonengelhardt** [comment]
@kevinhermawan Yeah, I noticed that too.

But many other apps have their own auto update feature and still a homebrew cask (Nextcloud, Rectangle, ...)

Another reason for homebrew is the Brewfile, with which you can easily set up new Mac's with one command.

**Comment by mattbisme** [comment]
If I had to pick, I always prefer the Sparkle/Check for updates menu item over homebrew. Something like homebrew seems a bit overkill for such a simple, low-dependency, app.

**Comment by djpowers** [comment]
I just discovered Ollamac today and it's a great app! I'd like to echo the request for it to be listed on Homebrew. Like @antonengelhardt mentioned, I make use of [Homebrew Bundle](https://github.com/Homebrew/homebrew-bundle), which I sync across machines to ensure my desired applications are available on each device.

If it's not too much additional overhead to make the application available on Homebrew, I would find it very beneficial for the automation installation process it would provide.

Thanks for the work on the project and for considering this request!

**Comment by antonengelhardt** [comment]
@djpowers have you ever done it before? If the maintainers are ok with it, maybe we can try it ?

**Comment by kevinhermawan** [comment]
Hi friends, sorry for the delayed response. Currently, my main focus is completing [Ollamac 2](https://github.com/kevinhermawan/Ollamac/issues/31). I found you guys interesting on Homebrew, so I'll experiment with it once I complete the roadmap.

**Comment by cliffordh** [comment]
I would put it to a community poll

**Comment by antonengelhardt** [comment]
@kevinhermawan Sounds good. Thanks for the awesome repo and the answers! ❤️

**Comment by djpowers** [comment]
Thanks @kevinhermawan, looking forward to v2! And I haven't gone through the process of adding a new cask before @antonengelhardt, but the documentation looks pretty straightforward: https://docs.brew.sh/Adding-Software-to-Homebrew#casks

**Comment by dcchambers** [comment]
I prefer to manage as much as I can via homebrew (I also use [homebrew bundle](https://github.com/Homebrew/homebrew-bundle) for managing apps between multiple systems). Although the app is easy to install from the release page and it has a self-updating feature, there's really no downside IMO to having an install available via Homebrew.

I went ahead and opened up a PR to add a cask for Ollamac: https://github.com/Homebrew/homebrew-cask/pull/166353

I believe the app meets all the criteria for being adding to the core Homebrew cask repo, so hopefully it gets merged 🤞

**Comment by antonengelhardt** [comment]
@dcchambers Nice!! Thanks a lot. I agree that the installation via GitHub is easy but with Homebrew you just have more options. Also, any guide or developer documentation can now have users download Ollama and Ollamac with two commands, as Ollama is also available via Homebrew. 

Cheers!

**Comment by mattbisme** [comment]
Ollama has been available on Homebrew for a while now. However, the Homebrew version always seems to stay behind the releases.

**Comment by dcchambers** [comment]
@mattbisme A couple of months ago they released a cask version which installs a little GUI used to manage the CLI. That cask version seems to be updated regularly and does not fall behind the version they have [on their website](https://ollama.com/download). Not sure why they prefer it done this way, but 🤷. If using the cask version of Ollama you're not supposed to use the one form `homebrew-core`

**Comment by mattbisme** [comment]
> @mattbisme A couple of months ago they released a cask version which installs a little GUI used to manage the CLI. That cask version seems to be updated regularly and does not fall behind the version they have [on their website](https://ollama.com/download). Not sure why they prefer it done this way, but 🤷. If using the cask version of Ollama you're not supposed to use the one form `homebrew-core`

@dcchambers So, it's not just the usual `homebrew install ollama`? Where can I find the cask info?

**Comment by dcchambers** [comment]
@mattbisme yep, `brew install --cask ollama` is what you want now. ([cask](https://github.com/Homebrew/homebrew-cask) is used to install `.app` applications via homebrew).

https://formulae.brew.sh/cask/ollama - current version in the cask registry is 0.1.24 which is the same as the one available for download from https://ollama.com.

I'd probably uninstall the other version first `brew uninstall ollama` if you want to use the cask version. There is no need to have both. Unsure if the ollama team intends to deprecate the standard formula or if they will keep supporting both of them.

**Comment by dcchambers** [comment]
Done, Ollamac is now available in Homebrew: #Homebrew/homebrew-cask#166353

`brew install --cask ollamac` 🎉

**Comment by kevinhermawan** [comment]
Thanks a lot, @dcchambers & friends! 🫡
