### ISSUE TITLE
Build for Ventura 13.x

### ISSUE THREAD

**Issue by fuad00** [kevinhermawan/Ollamac#44]
![CleanShot 2024-02-22 at 01 47 10@2x](https://github.com/kevinhermawan/Ollamac/assets/26776550/b0054336-5b24-43a7-a000-7d4dc1e55229)

**Comment by replete** [comment]
![Screenshot 2024-02-22 at 00 27 37](https://github.com/kevinhermawan/Ollamac/assets/812139/418c3d0e-c2ad-4eec-bcef-ff3bfba682b5)

:(

**Comment by kevinhermawan** [comment]
Apologies, but we cannot add compatibility for macOS before Sonoma as Ollamac requires macOS Sonoma APIs.
