### ISSUE TITLE
Remove SUEnableDownloaderService key in Info.plist

### ISSUE THREAD

**Issue by zorgiepoo** [kevinhermawan/Ollamac#45]
Due to a sandboxing issue new to macOS Sonoma, users may see a one-time warning when checking for updates about "Downloader" differs from previously opened versions.

Ollamac can simply resolve this issue by removing the SUEnableDownloaderService key in the app's Info.plist. This app is already entitled with `com.apple.security.network.client` and does not have a reason to use Sparkle's downloader service.

See [this discussion](https://github.com/sparkle-project/Sparkle/discussions/2514) for more information.

**Comment by kevinhermawan** [comment]
Hi @zorgiepoo, thank you for the information. I will look into it.
