### ISSUE TITLE
Previously deleted models still show in model select

### ISSUE THREAD

**Issue by tsegreto** [kevinhermawan/Ollamac#48]
Previously deleted models still show in model select, when you select them it says: "This model is currently unavailable or has been removed" Strange you wouldn't use the model list feature on load to get all the available models, no reason to cache them.

**Comment by kevinhermawan** [comment]
Just released [v2.0.0](https://github.com/kevinhermawan/Ollamac/releases/tag/v2.0.0). And this case will not happen again in the next version. Thank you!
