### ISSUE TITLE
[Feature Request] System Prompts for models

### ISSUE THREAD

**Issue by FlipTip** [kevinhermawan/Ollamac#49]

**Comment by Cohibastyle** [comment]
To be able to select a default model, at launch, without having to select a model.

**Comment by rb81** [comment]
@FlipTip - If you create a model from a custom modelfile, you can customize your system prompt as well as the model parameters, then just select it as a model from the model list.

+1 to be able to select a default model though.

**Comment by kevinhermawan** [comment]
Now available in [v3.0.0](https://github.com/kevinhermawan/Ollamac/releases/tag/v3.0.0)!
