### ISSUE TITLE
Simpler new-chat experience (no pop-up prompt)

### ISSUE THREAD

**Issue by epheterson** [kevinhermawan/Ollamac#50]
The pop-up prompt asking for a chat name and model is sort of unnecessary.

It'd be simpler to get right to the chat UI, where the chat name can be optionally edited, and the model is pre-selected.

In my case, there's only one model so that's simple. Otherwise you could default to the last-used model and allow changing before the first message with a drop-down. Maybe you could define a default?

If the user doesn't update the name after the first message or so, use that model with the contents to come up with a name like the chat sites do.

Great app, thanks for considering!

**Comment by Madnex** [comment]
Any update on this? A new chat should be a one click experience indeed if possible.

**Comment by kevinhermawan** [comment]
Stay tuned! Hopefully, I can work on this over the weekend! 👀

**Comment by kevinhermawan** [comment]
Now available in [v3.0.0](https://github.com/kevinhermawan/Ollamac/releases/tag/v3.0.0)!
