### ISSUE TITLE
Signing the App (Unknown Developer Warning)

### ISSUE THREAD

**Issue by rb81** [kevinhermawan/Ollamac#51]
I'm sure you're already aware, but not signing your app results in an "unknown developer" warning when running the installer. What's keeping you guys from doing so?

<img width="372" alt="Screenshot 2024-04-25 at 7 47 35 PM" src="https://github.com/kevinhermawan/Ollamac/assets/48117105/18fcb436-c329-4203-b3fa-3230e946d443">

**Comment by aakashbondwal** [comment]
1. In the Finder  on your Mac, locate the app you want to open.
2. Don’t use Launchpad to do this. Launchpad doesn’t allow you to access the shortcut menu.
3. Control-click the app icon, then choose Open from the shortcut menu.
4. Click Open.

Try this

**Comment by rb81** [comment]
@aakashbondwal Bypassing Apple's security wasn't what I was looking for, but thank you :)
Getting this fixed doesn't take much effort and ensures the app is reviewed and trusted.

**Comment by kevinhermawan** [comment]
Just released [v1.2.0](https://github.com/kevinhermawan/Ollamac/releases/tag/v1.2.0). And this case will not happen again in the next version. Thank you!

**Comment by rb81** [comment]
> Just released [v1.2.0](https://github.com/kevinhermawan/Ollamac/releases/tag/v1.2.0). And this case will not happen again in the next version. Thank you!

Thanks for fixing this! Loving the app. Well done.
