### ISSUE TITLE
Auto-Generate Titles

### ISSUE THREAD

**Issue by rb81** [kevinhermawan/Ollamac#56]
Open-WebUI does this well: Option to select a model to auto-generate conversation titles. Would be even better to select after how many messages to do so -- Open-WebUI does this after the first message (as it seems) and the titles are often nonsensical if the first message is "hello" or some useless start.

**Comment by kevinhermawan** [comment]
Yes, I am also planning for that. 😃

**Comment by kevinhermawan** [comment]
Now available in [v3.0.0](https://github.com/kevinhermawan/Ollamac/releases/tag/v3.0.0)!
