### ISSUE TITLE
Ollamac tries to connect to IP 100.100.100.100

### ISSUE THREAD

**Issue by ibehnam** [kevinhermawan/Ollamac#59]
What is this IP address that Ollamac wants to connect to? I declined this request and Ollamac still works fine. Is it some sort of telemetry?

<img width="739" alt="2024-05-27_12 37 03" src="https://github.com/kevinhermawan/Ollamac/assets/58621210/0a2a5ecc-83aa-4726-b4de-e2b30e78c570">

**Comment by kevinhermawan** [comment]
Hi @ibehnam, that's strange. Ollamac doesn't connect to the IP address 100.100.100.100. It only connects to the Ollama server. The IP address you mentioned is associated with Tailscale's documentation (https://tailscale.com/kb/1381/what-is-quad100), which might provide more context.

**Comment by pmarreck** [comment]
@ibehnam that's your tailscale install interfering, my dude
