### ISSUE TITLE
External server

### ISSUE THREAD

**Issue by TijuanaKez** [kevinhermawan/Ollamac#60]
I like the interface and colours, but I can't run Ollama efficiently on my Mac.
I do have it running on a linux box with a 3090 on my LAN though!
Can you please add a setting to choose between localhost and a LAN ip for the server connection like OpenWebUI?

**Comment by rb81** [comment]
+1 on this. I also run Ollama on a different machine so configuring the endpoint would be useful.

**Comment by reestr** [comment]
This request would be a duplicate of https://github.com/kevinhermawan/Ollamac/issues/2

**Comment by kevinhermawan** [comment]
Hey everyone! Finally, we can close this issue now. Check out the features in the [new update](https://github.com/kevinhermawan/Ollamac/releases/tag/v2.1.0)! 😉
