### ISSUE TITLE
2.0 crash 

### ISSUE THREAD

**Issue by jjllrrvvrr** [kevinhermawan/Ollamac#64]
The program crashes at startup since the update

**Comment by kevinhermawan** [comment]
Hmm, have you tried reinstalling it?

**Comment by jjllrrvvrr** [comment]
I did, also remove and install again. 
sorry I can't give you more infos.

I'm on M2pro, last update.

**Comment by kevinhermawan** [comment]
Did you install it using Homebrew or download it directly?

**Comment by kevinhermawan** [comment]
Could you please run this command in your terminal?

`rm -rf ~/Library/Containers/com.kevinhermawan.Ollamac/Data/Library/Application\ Support/`

**Comment by jjllrrvvrr** [comment]
It's work! Thanks you

**Comment by kevinhermawan** [comment]
You're welcome!

**Comment by tuc0w** [comment]
Fixed it for me, thanks!
