### ISSUE TITLE
I just upgraded and it does not start

### ISSUE THREAD

**Issue by verhas** [kevinhermawan/Ollamac#65]
The application told me to upgrade itself, and the new version crashes at start.

**Comment by sljmn** [comment]
delete the old app, reinstall the new one from the release page https://github.com/kevinhermawan/Ollamac/releases

**Comment by kangaroo** [comment]
Or just delete the old store:

`rm -rf ~/Library/Containers/com.kevinhermawan.Ollamac `

**Comment by kevinhermawan** [comment]
Can you please check the solution I suggested in #64 to see if it resolves the issue?

**Comment by gentax** [comment]
> Or just delete the old store:
> 
> `rm -rf ~/Library/Containers/com.kevinhermawan.Ollamac `

Thanks. This fix the issue and Ollamac v2 stated as expected.
