### ISSUE TITLE
Ollamac quit unexpectedly after update to 2.0

### ISSUE THREAD

**Issue by Richard-CokeCola** [kevinhermawan/Ollamac#66]
after update to 2.0, Ollamac quit unexpectedly every time when opened, and reopen did not work. It just cannot open anymore.

**Comment by Richard-CokeCola** [comment]
Process:               Ollamac [37387]
Path:                  /Applications/Ollamac.app/Contents/MacOS/Ollamac
Identifier:            com.kevinhermawan.Ollamac
Version:               2.0.0 (8)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               503

Date/Time:             2024-06-13 19:08:26.0552 +0800
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Bridge OS Version:     8.5 (21P5077)
Anonymous UUID:        952F31B4-A96C-5E2D-47B7-E5B8526F01EC

Sleep/Wake UUID:       0D6B5B89-A701-49A4-BB5D-F912BA5C3939

Time Awake Since Boot: 370000 seconds
Time Since Wake:       4989 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [37387]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	    0x7ff816f06d9f _assertionFailure(_:_:file:line:flags:) + 351
1   Ollamac                       	       0x10e7010ad 0x10e6dd000 + 147629
2   Ollamac                       	       0x10e70295f 0x10e6dd000 + 153951
3   Ollamac                       	       0x10e7022c5 0x10e6dd000 + 152261
4   SwiftUI                       	    0x7ff913ebe3f1 0x7ff91330d000 + 12260337
5   Ollamac                       	       0x10e70231e 0x10e6dd000 + 152350
6   dyld                          	    0x7ff8064ad366 start + 1942

Thread 1:
0   libsystem_pthread.dylib       	    0x7ff806834ac0 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff806834ac0 start_wqthread + 0


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000200000003  rbx: 0x000000010e7f5640  rcx: 0xfffffffe00000000  rdx: 0x0000000000000003
  rdi: 0x0000600003839808  rsi: 0x0000000000000d80  rbp: 0x00007ff7b1822500  rsp: 0x00007ff7b1822460
   r8: 0x000000000000007f   r9: 0x00000000b602e81c  r10: 0x000000000000005d  r11: 0x0000000000000020
  r12: 0x000000010e7f53d0  r13: 0x0000000000000070  r14: 0x0000600003839800  r15: 0x000000000000000b
  rip: 0x00007ff816f06d9f  rfl: 0x0000000000010246  cr2: 0x0000000000000000
  
Logical CPU:     6
Error Code:      0x00000000 
Trap Number:     6

Thread 0 instruction stream:
  9e 00 00 00 48 b8 00 00-00 00 00 00 00 10 49 85  ....H.........I.
  c5 0f 84 7f 01 00 00 48-ff c8 4c 89 f7 48 21 c7  .......H..L..H!.
  48 83 c7 20 48 b8 ff ff-ff ff ff ff 00 00 49 21  H.. H.........I!
  c5 48 83 ec 08 44 0f b6-c1 4c 89 ee 4c 89 e2 48  .H...D...L..L..H
  8b 4d 10 49 89 d9 8b 45-28 50 ff 75 20 41 57 e8  .M.I...E(P.u AW.
  bd 0e 00 00 48 83 c4 20-4c 89 f7 e8 a1 ed 32 00  ....H.. L.....2.
 [0f]0b 48 83 ec 08 48 8d-05 c4 8f 44 00 48 8d 3d  ..H...H....D.H.=	<==
  31 8b 44 00 48 8d 0d 46-8e 44 00 be 0b 00 00 00  1.D.H..F.D......
  41 b8 39 00 00 00 ba 02-00 00 00 41 b9 02 00 00  A.9........A....
  00 6a 01 68 94 00 00 00-6a 02 6a 18 50 e8 3f 02  .j.h....j.j.P.?.
  00 00 4c 89 f6 48 c1 ee-38 83 e6 0f 48 b8 ff ff  ..L..H..8...H...
  ff ff ff ff ff 00 4c 21-f0 4c 89 6d c0 48 89 45  ......L!.L.m.H.E

Binary Images:
       0x10ea35000 -        0x10ea41fff libobjc-trampolines.dylib (*) <caf1eb21-6511-3736-9b71-deedf5e9226b> /usr/lib/libobjc-trampolines.dylib
       0x10ee41000 -        0x10ee84fff org.sparkle-project.Sparkle (2.5.1) <c48058fc-540e-3b1f-af01-3260e00c3e1d> /Applications/Ollamac.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle
       0x10e6dd000 -        0x10e81dfff com.kevinhermawan.Ollamac (2.0.0) <cc31d3a6-7f1a-3054-a8e2-687260d34af6> /Applications/Ollamac.app/Contents/MacOS/Ollamac
    0x7ff816ed8000 -     0x7ff817389fff libswiftCore.dylib (*) <37e40068-5079-36e0-b908-daf2333cc726> /usr/lib/swift/libswiftCore.dylib
    0x7ff91330d000 -     0x7ff914e57ff8 com.apple.SwiftUI (5.5.8) <4bdb26b5-5fb0-3445-8416-d482fbdc082f> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
    0x7ff8064a7000 -     0x7ff806537b9f dyld (*) <baa6f02e-dff3-3562-8c99-ea2820c91ad9> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
    0x7ff806833000 -     0x7ff80683eff7 libsystem_pthread.dylib (*) <25b2f3eb-07b4-3cb9-9457-2c26210c27c8> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=821.3M resident=0K(0%) swapped_out_or_unallocated=821.3M(100%)
Writable regions: Total=1.5G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
CoreData Object IDs               4100K        2 
Foundation                          16K        1 
Kernel Alloc Once                    8K        1 
MALLOC                             1.5G       34 
MALLOC guard page                   24K        6 
STACK GUARD                       56.0M        3 
Stack                             9232K        3 
VM_ALLOCATE                          4K        1 
__CTF                               824        1 
__DATA                            32.2M      511 
__DATA_CONST                      37.4M      330 
__DATA_DIRTY                      1763K      188 
__FONT_DATA                        2352        1 
__LINKEDIT                       180.5M        5 
__OBJC_RO                         71.8M        1 
__OBJC_RW                         2200K        2 
__TEXT                           640.8M      534 
dyld private memory                260K        2 
mapped file                       31.3M        4 
shared memory                     1120K        9 
===========                     =======  ======= 
TOTAL                              2.5G     1640 



-----------
Full Report
-----------

{"app_name":"Ollamac","timestamp":"2024-06-13 19:08:26.00 +0800","app_version":"2.0.0","slice_uuid":"cc31d3a6-7f1a-3054-a8e2-687260d34af6","build_version":"8","platform":1,"bundleID":"com.kevinhermawan.Ollamac","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.5 (23F79)","roots_installed":0,"name":"Ollamac","incident_id":"D00DA244-6E27-4DAF-8D48-B12D6AA0E280"}
{
  "uptime" : 370000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 503,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro16,1",
  "coalitionID" : 67606,
  "osVersion" : {
    "train" : "macOS 14.5",
    "build" : "23F79",
    "releaseType" : "User"
  },
  "captureTime" : "2024-06-13 19:08:26.0552 +0800",
  "codeSigningMonitor" : 0,
  "incident" : "D00DA244-6E27-4DAF-8D48-B12D6AA0E280",
  "pid" : 37387,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-06-13 19:08:23.0297 +0800",
  "procStartAbsTime" : 371008322462873,
  "procExitAbsTime" : 371011347434396,
  "procName" : "Ollamac",
  "procPath" : "\/Applications\/Ollamac.app\/Contents\/MacOS\/Ollamac",
  "bundleInfo" : {"CFBundleShortVersionString":"2.0.0","CFBundleVersion":"8","CFBundleIdentifier":"com.kevinhermawan.Ollamac"},
  "storeInfo" : {"deviceIdentifierForVendor":"9E34D299-8B76-5AC6-A3F8-0A654C6CCF4D","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.kevinhermawan.Ollamac",
  "crashReporterKey" : "952F31B4-A96C-5E2D-47B7-E5B8526F01EC",
  "codeSigningID" : "com.kevinhermawan.Ollamac",
  "codeSigningTeamID" : "84ZM7K56B5",
  "codeSigningFlags" : 570503953,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 4294967295,
  "wakeTime" : 4989,
  "bridgeVersion" : {"build":"21P5077","train":"8.5"},
  "sleepWakeUUID" : "0D6B5B89-A701-49A4-BB5D-F912BA5C3939",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_INSTRUCTION","signal":"SIGILL"},
  "termination" : {"flags":0,"code":4,"namespace":"SIGNAL","indicator":"Illegal instruction: 4","byProc":"exc handler","byPid":37387},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":20842366,"instructionState":{"instructionStream":{"bytes":[158,0,0,0,72,184,0,0,0,0,0,0,0,16,73,133,197,15,132,127,1,0,0,72,255,200,76,137,247,72,33,199,72,131,199,32,72,184,255,255,255,255,255,255,0,0,73,33,197,72,131,236,8,68,15,182,193,76,137,238,76,137,226,72,139,77,16,73,137,217,139,69,40,80,255,117,32,65,87,232,189,14,0,0,72,131,196,32,76,137,247,232,161,237,50,0,15,11,72,131,236,8,72,141,5,196,143,68,0,72,141,61,49,139,68,0,72,141,13,70,142,68,0,190,11,0,0,0,65,184,57,0,0,0,186,2,0,0,0,65,185,2,0,0,0,106,1,104,148,0,0,0,106,2,106,24,80,232,63,2,0,0,76,137,246,72,193,238,56,131,230,15,72,184,255,255,255,255,255,255,255,0,76,33,240,76,137,109,192,72,137,69],"offset":96}},"threadState":{"r13":{"value":112},"rax":{"value":8589934595},"rflags":{"value":66118},"cpu":{"value":6},"r14":{"value":105553175222272},"rsi":{"value":3456},"r8":{"value":127},"cr2":{"value":0},"rdx":{"value":3},"r10":{"value":93},"r9":{"value":3053643804},"r15":{"value":11},"rbx":{"value":4538193472},"trap":{"value":6},"err":{"value":0},"r11":{"value":32},"rip":{"value":140703513472415,"matchesCrashFrame":1},"rbp":{"value":140701811746048},"rsp":{"value":140701811745888},"r12":{"value":4538192848},"rcx":{"value":18446744065119617024},"flavor":"x86_THREAD_STATE","rdi":{"value":105553175222280}},"queue":"com.apple.main-thread","frames":[{"imageOffset":191903,"symbol":"_assertionFailure(_:_:file:line:flags:)","symbolLocation":351,"imageIndex":3},{"imageOffset":147629,"imageIndex":2},{"imageOffset":153951,"imageIndex":2},{"imageOffset":152261,"imageIndex":2},{"imageOffset":12260337,"imageIndex":4},{"imageOffset":152350,"imageIndex":2},{"imageOffset":25446,"symbol":"start","symbolLocation":1942,"imageIndex":5}]},{"id":20842647,"frames":[{"imageOffset":6848,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"r13":{"value":0},"rax":{"value":33554800},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":6919},"r8":{"value":409604},"cr2":{"value":0},"rdx":{"value":123145532682240},"r10":{"value":0},"r9":{"value":18446744073709551615},"r15":{"value":0},"rbx":{"value":123145533206528},"trap":{"value":133},"err":{"value":33554800},"r11":{"value":582},"rip":{"value":140703237884608},"rbp":{"value":0},"rsp":{"value":123145533206528},"r12":{"value":0},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":123145533206528}}},{"id":20842648,"frames":[{"imageOffset":6848,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"r13":{"value":0},"rax":{"value":33554800},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":10499},"r8":{"value":409604},"cr2":{"value":0},"rdx":{"value":123145533218816},"r10":{"value":0},"r9":{"value":18446744073709551615},"r15":{"value":123145533741944},"rbx":{"value":123145533743104},"trap":{"value":133},"err":{"value":33554800},"r11":{"value":582},"rip":{"value":140703237884608},"rbp":{"value":0},"rsp":{"value":123145533743104},"r12":{"value":5193732},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":123145533743104}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64h",
    "base" : 4540551168,
    "size" : 53248,
    "uuid" : "caf1eb21-6511-3736-9b71-deedf5e9226b",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4544794624,
    "CFBundleShortVersionString" : "2.5.1",
    "CFBundleIdentifier" : "org.sparkle-project.Sparkle",
    "size" : 278528,
    "uuid" : "c48058fc-540e-3b1f-af01-3260e00c3e1d",
    "path" : "\/Applications\/Ollamac.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle",
    "name" : "Sparkle",
    "CFBundleVersion" : "2032"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4537044992,
    "CFBundleShortVersionString" : "2.0.0",
    "CFBundleIdentifier" : "com.kevinhermawan.Ollamac",
    "size" : 1314816,
    "uuid" : "cc31d3a6-7f1a-3054-a8e2-687260d34af6",
    "path" : "\/Applications\/Ollamac.app\/Contents\/MacOS\/Ollamac",
    "name" : "Ollamac",
    "CFBundleVersion" : "8"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703513280512,
    "size" : 4923392,
    "uuid" : "37e40068-5079-36e0-b908-daf2333cc726",
    "path" : "\/usr\/lib\/swift\/libswiftCore.dylib",
    "name" : "libswiftCore.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140707745550336,
    "CFBundleShortVersionString" : "5.5.8",
    "CFBundleIdentifier" : "com.apple.SwiftUI",
    "size" : 28618745,
    "uuid" : "4bdb26b5-5fb0-3445-8416-d482fbdc082f",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/Versions\/A\/SwiftUI",
    "name" : "SwiftUI",
    "CFBundleVersion" : "5.5.8"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703234158592,
    "size" : 592800,
    "uuid" : "baa6f02e-dff3-3562-8c99-ea2820c91ad9",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703237877760,
    "size" : 49144,
    "uuid" : "25b2f3eb-07b4-3cb9-9457-2c26210c27c8",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 140703233462272,
  "size" : 25769803776,
  "uuid" : "b48cfc6b-b7ed-3343-97fb-f5187dc04df8"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=821.3M resident=0K(0%) swapped_out_or_unallocated=821.3M(100%)\nWritable regions: Total=1.5G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nCoreData Object IDs               4100K        2 \nFoundation                          16K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                             1.5G       34 \nMALLOC guard page                   24K        6 \nSTACK GUARD                       56.0M        3 \nStack                             9232K        3 \nVM_ALLOCATE                          4K        1 \n__CTF                               824        1 \n__DATA                            32.2M      511 \n__DATA_CONST                      37.4M      330 \n__DATA_DIRTY                      1763K      188 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       180.5M        5 \n__OBJC_RO                         71.8M        1 \n__OBJC_RW                         2200K        2 \n__TEXT                           640.8M      534 \ndyld private memory                260K        2 \nmapped file                       31.3M        4 \nshared memory                     1120K        9 \n===========                     =======  ======= \nTOTAL                              2.5G     1640 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "202a28fdf62e446d6e566c136cc82e7dcad3348b",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "648c94d4ebdf9e3e398fa708",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_NL_OVERRIDES" : "65a8104b6712a43e7922cab8"
      },
      "deploymentId" : 240000171
    },
    {
      "rolloutId" : "645197bf528fbf3c3af54105",
      "factorPackIds" : {
        "SIRI_VALUE_INFERENCE_PERVASIVE_ENTITY_RESOLUTION" : "663e65b4a1526e1ca0e288a1"
      },
      "deploymentId" : 240000002
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "3dff9c91-a8fb-424e-a656-c8d6e6037574",
      "experimentId" : "662152ede2d11d1408c4db33",
      "deploymentId" : 400000010
    },
    {
      "treatmentId" : "45f4e2a5-551b-4bc2-a2dc-19c244dda8f8",
      "experimentId" : "6643969b3099cf28e049862f",
      "deploymentId" : 400000002
    }
  ]
}
}

Model: MacBookPro16,1, BootROM 2022.100.22.0.0 (iBridge: 21.16.5077.0.0,0), 8 processors, 8-Core Intel Core i9, 2.3 GHz, 32 GB, SMC 
Graphics: Intel UHD Graphics 630, Intel UHD Graphics 630, Built-In
Graphics: AMD Radeon Pro 5500M, AMD Radeon Pro 5500M, PCIe, 4 GB
Display: Color LCD, 3072 x 1920 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/ChannelA-DIMM0, 16 GB, DDR4, 2667 MHz, Micron, MT40A2G8NEA-062E:J
Memory Module: BANK 2/ChannelB-DIMM0, 16 GB, DDR4, 2667 MHz, Micron, MT40A2G8NEA-062E:J
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x7BF), wl0: Jul 10 2023 12:53:18 version 9.30.503.0.32.5.92 FWID 01-c06f991b
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: T2Bus
USB Device: composite_device
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 63.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 63.5

**Comment by kevinhermawan** [comment]
These closed issues may help you:

https://github.com/kevinhermawan/Ollamac/issues/65 & https://github.com/kevinhermawan/Ollamac/issues/64
