### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by cmulder7** [kevinhermawan/Ollamac#67]
updated to v2 and now it crashes when I open it. Ran the crash report through Llama 3 and got this

Based on the information provided, it appears that the issue is related to 
a breakpoint being hit in the `Ollamac` app. Specifically:

* The crashed thread is Thread 0, which is running on the main dispatch 
queue (`com.apple.main-thread`).
* The exception type is `EXC_BREAKPOINT`, which indicates that a 
breakpoint was hit.
* The terminating process is `exc handler [3314]`, which suggests that the 
app's runtime (e.g., Swift) attempted to handle the breakpoint, but 
ultimately terminated due to the error.

**Comment by jjborie** [comment]
Same here.

**Comment by kevinhermawan** [comment]
These closed issues may help you:

https://github.com/kevinhermawan/Ollamac/issues/65 & https://github.com/kevinhermawan/Ollamac/issues/64

**Comment by jjborie** [comment]
> These closed issues may help you:
> 
> #65 & #64
Used:
rm -rf ~/Library/Containers/com.kevinhermawan.Ollamac

and it worked, thanks @kevinhermawan !
