### ISSUE TITLE
Code Syntax Highlight View

### ISSUE THREAD

**Issue by khairu-aqsara** [kevinhermawan/Ollamac#70]
This is not an issue, as long as there are features like Code Syntax Highlight View available, which Swift-Markdown-UI provides. Perhaps this can be one of the features for the next release.

**Comment by kevinhermawan** [comment]
Implemented in [version 2.1.0](https://github.com/kevinhermawan/Ollamac/releases/tag/v2.1.0), enjoy! 😉

**Comment by khairu-aqsara** [comment]
wow that was fast, muanteb mas ✌️
