### ISSUE TITLE
Ollamac crashes at start

### ISSUE THREAD

**Issue by SRachmaninov** [kevinhermawan/Ollamac#73]
Hello Ollamac Comunity,

When I first installed Ollama on my Macbook M1 Pro 2021 16-inch running Sonoma 14.5 everything worked perfectly fine.
Recently, it crashes every time I try to open it. Unfortunately, I can't link it to a system, Ollama or Ollamac update to identify the culprit.
I've uploaded the crash log file as a txt-file here.
[Ollamac Error Log.txt](https://github.com/user-attachments/files/16120714/Ollamac.Error.Log.txt)

Any help is highly appreciated.
Thanks!

**Comment by kevinhermawan** [comment]
These closed issues may help you:

https://github.com/kevinhermawan/Ollamac/issues/65 & https://github.com/kevinhermawan/Ollamac/issues/64

**Comment by SRachmaninov** [comment]
Thanks so much, [#64](https://github.com/kevinhermawan/Ollamac/issues/64) worked! 
Sorry, I should have looked a little bit more thoroughly in the issues that have been discussed already...

**Comment by kevinhermawan** [comment]
You're welcome!
