### ISSUE TITLE
not discovering ollama

### ISSUE THREAD

**Issue by ageorgios** [kevinhermawan/Ollamac#9]
![Screenshot 2023-11-13 at 12 31 18](https://github.com/kevinhermawan/Ollamac/assets/3126351/0b7b90b4-669b-4bc2-9eb6-480820d9158e)

I get this although 

![image](https://github.com/kevinhermawan/Ollamac/assets/3126351/a8f31673-b01e-4e3d-bc9a-05c3d2402cfe)

what am I doing wrong ?

**Comment by kevinhermawan** [comment]
Hello @ageorgios, the error message you're encountering doesn't seem to be related to connectivity issues with the API. To troubleshoot further, could you please check if you're using a VPN or have any network firewalls that might be interfering with the connection? Sometimes these can create unexpected issues. Additionally, it might help to completely close the Ollamac and then reopen it. This can often resolve temporary glitches. Let me know how it goes!

**Comment by ageorgios** [comment]
no VPN or network firewalls.
restarted.. same problem!
cannot understand why

**Comment by ageorgios** [comment]
I built the project in Xcode
and when I press new chat 
this is the log message:
nw_socket_handle_socket_event [C1.1.1:2] Socket SO_ERROR 61

**Comment by ageorgios** [comment]
I also get 200 on the ollama server!
OLLAMA_ORIGINS=* OLLAMA_HOST=0.0.0.0:11434 ollama serve
```
2023/11/13 21:43:04 images.go:824: total blobs: 155
2023/11/13 21:43:04 images.go:831: total unused blobs removed: 116
2023/11/13 21:43:04 routes.go:696: Listening on [::]:11434 (version 0.1.9)
[GIN] 2023/11/13 - 21:43:08 | 200 |      48.916µs |             ::1 | HEAD     "/"
[GIN] 2023/11/13 - 21:43:08 | 200 |    3.385292ms |             ::1 | GET      "/api/tags"
```

**Comment by ageorgios** [comment]
try await ollamaViewModel.fetch()
for some reason this throws exception

**Comment by kevinhermawan** [comment]
For now, we can ignore `nw_socket_handle_socket_event [C1.1.1:2] Socket SO_ERROR 61` warning.

**Comment by kevinhermawan** [comment]
Does the release version have the same issue?

**Comment by ageorgios** [comment]
yes I first downloaded the release, then decided to download the project to check why

**Comment by kevinhermawan** [comment]
I can't produce this issue. However, I noticed that compared to mine, there's a different `modified_at` date format in use here.

![CleanShot 2023-11-14 at 04 30 17](https://github.com/kevinhermawan/Ollamac/assets/84965338/1082c7b8-0149-46ea-91a5-36bce763478b)

**Comment by kevinhermawan** [comment]
Thanks for providing the JSON response,  I will attempt to mock the response using that JSON and will inform you of the results. 😃

**Comment by ageorgios** [comment]
Thanks really appreciate it

**Comment by kevinhermawan** [comment]
Hi @ageorgios, a fix has been implemented in this latest release. Could you please review and test it to confirm if it's working as expected?

**Comment by ageorgios** [comment]
Working as expected! thank you very much!

**Comment by kevinhermawan** [comment]
Thanks for the confirmation @ageorgios! I will close this issue.
